"""DevFlow notify command group — notification service scaffolding.

Depends on devflow integrate — if no provider is configured for the channel,
prints the exact integrate command to run. Test is blocked in production.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Annotated, Optional

import typer
from rich.panel import Panel
from rich.table import Table

from devflow.console import console

app = typer.Typer(help="Notification service scaffolding.")

# Notification type → expected integration category
_CHANNEL_MAP: dict[str, str] = {
    "EmailNotification": "email",
    "PushNotification": "notify",
    "SMSNotification": "notify",
}


def _detect_provider(channel: str, output_root: Path) -> Optional[str]:
    """Detect whether a provider for the given channel is already integrated.

    Args:
        channel: Integration category, e.g. 'email' or 'notify'.
        output_root: Project output root directory.

    Returns:
        Provider name if found, else None.
    """
    integrations_dir = output_root / "integrations" / channel
    if not integrations_dir.exists():
        return None
    for sub in integrations_dir.iterdir():
        if sub.is_dir() and (sub / "service.py").exists():
            return sub.name
    return None


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


@app.command("init")
def notify_init() -> None:
    """Initialise the notification module for this project.

    Creates notifications/__init__.py and checks that at least one provider
    is integrated. Prints the exact integrate command if no provider is found.
    """
    from devflow.config import get_config

    cfg = get_config()
    output_root = Path.cwd() / cfg.output_dir
    notif_dir = output_root / "notifications"
    notif_dir.mkdir(parents=True, exist_ok=True)
    (notif_dir / "__init__.py").touch(exist_ok=True)
    console.print(f"  [green]✅[/green] Created: [cyan]{notif_dir}[/cyan]")
    console.print(
        Panel(
            "[green]✅ Notifications directory ready.[/green]\n\n"
            "Next, generate a notification class:\n"
            "  [cyan]devflow notify generate EmailNotification[/cyan]\n"
            "  [cyan]devflow notify generate PushNotification[/cyan]\n"
            "  [cyan]devflow notify generate SMSNotification[/cyan]",
            border_style="green",
        )
    )


@app.command("generate")
def notify_generate(
    notification_type: Annotated[
        str,
        typer.Argument(
            help="Notification class: EmailNotification | PushNotification | SMSNotification"
        ),
    ],
) -> None:
    """Generate a notification class for the configured provider.

    If no provider is integrated for the notification channel, prints the
    exact devflow integrate command to run first.

    Args:
        notification_type: One of EmailNotification, PushNotification, SMSNotification.
    """
    if notification_type not in _CHANNEL_MAP:
        from devflow.commands.smart_errors import smart_error

        smart_error(
            context=f"Unknown notification type '{notification_type}'.",
            typed=notification_type,
            candidates=list(_CHANNEL_MAP.keys()),
            fix_cmd="devflow notify generate EmailNotification",
            guide_topic="notify",
        )

    from devflow.config import get_config

    cfg = get_config()
    output_root = Path.cwd() / cfg.output_dir
    channel = _CHANNEL_MAP[notification_type]

    provider = _detect_provider(channel, output_root)
    if not provider:
        console.print(
            Panel(
                f"[yellow]⚠️  No {channel} provider found.\n\n"
                f"Set one up first:\n"
                f"  [cyan]devflow integrate --provider {channel}/sendgrid[/cyan]\n"
                f"  [cyan]devflow integrate --provider {channel}/mailgun[/cyan]\n"
                f"  [cyan]devflow integrate --provider {channel}/smtp[/cyan][/yellow]",
                border_style="yellow",
            )
        )
        raise typer.Exit(1)

    notif_dir = output_root / "notifications"
    notif_dir.mkdir(parents=True, exist_ok=True)

    import re

    snake = re.sub(r"(?<!^)(?=[A-Z])", "_", notification_type).lower()
    out_path = notif_dir / f"{snake}.py"

    content = f'''"""Notification class: {notification_type}.

Generated by DevFlow. Uses the {provider} provider for {channel} notifications.
"""
from __future__ import annotations

from integrations.{channel}.{provider}.service import {provider.capitalize()}Service
from core.logger import logger  # type: ignore[import]


class {notification_type}:
    """{notification_type} via {provider}.

    Attributes:
        _service: Underlying {provider} integration service.
    """

    def __init__(self) -> None:
        """Initialise with the {provider} service."""
        self._service = {provider.capitalize()}Service()

    async def send(self, recipient: str, subject: str, body: str) -> dict:
        """Send a {channel} notification.

        Args:
            recipient: Recipient identifier (email address, device token, etc.).
            subject: Message subject or title.
            body: Message body content.

        Returns:
            Provider response dict.
        """
        logger.info("Sending {{}} notification via {provider}", "{notification_type}")
        return await self._service.send({{
            "recipient": recipient,
            "subject": subject,
            "body": body,
        }})
'''
    out_path.write_text(content, encoding="utf-8")
    console.print(f"  [green]✅[/green] Generated: [cyan]{out_path}[/cyan]")
    console.print(
        Panel(
            f"[green]✅ {notification_type} generated using {provider}.[/green]",
            border_style="green",
        )
    )


@app.command("test")
def notify_test(
    notification_type: Annotated[
        str,
        typer.Option("--type", help="Notification type: email | push | sms"),
    ] = "email",
    to: Annotated[str, typer.Option("--to", help="Test recipient address")] = "",
) -> None:
    """Send a test notification (blocked in production).

    Args:
        notification_type: Channel type (email, push, sms).
        to: Recipient address for the test message.
    """
    app_env = os.environ.get("APP_ENV", "development").lower()
    if app_env == "production":
        console.print(
            Panel(
                "[red]❌ Blocked: notification tests are disabled in production.\n"
                "Set APP_ENV to a non-production value to run tests.[/red]",
                border_style="red",
            )
        )
        raise typer.Exit(1)

    if not to:
        console.print("[red]❌ --to is required. Provide a recipient address.[/red]")
        raise typer.Exit(1)

    console.print(
        Panel(
            f"[green]✅ Test notification ({notification_type}) would be sent to: [cyan]{to}[/cyan][/green]\n"
            "[dim]Note: Actual sending requires the provider SDK and valid credentials.[/dim]",
            border_style="green",
        )
    )


@app.command("list")
def notify_list() -> None:
    """List all generated notification classes."""
    from devflow.config import get_config

    cfg = get_config()
    output_root = Path.cwd() / cfg.output_dir
    notif_dir = output_root / "notifications"

    if not notif_dir.exists():
        console.print(
            "[yellow]No notifications directory. Run: devflow notify init[/yellow]"
        )
        return

    files = [f for f in notif_dir.glob("*_notification.py") if f.name != "__init__.py"]
    if not files:
        console.print("[dim]No notification classes generated yet.[/dim]")
        return

    table = Table(title="⚡ Notification Classes", border_style="cyan")
    table.add_column("File", style="cyan")
    for f in sorted(files):
        table.add_row(f.name)
    console.print(table)
